package com.wjx.touhou_aifun.chat.agent;

/** Stable action guidance belongs in the cacheable policy, not every mutable checkpoint. */
public final class AgentTaskInstructions {
    private AgentTaskInstructions() { }
    public static final String POLICY = "## AIFun action execution rules\n"
            + "Match the owner's requested sources and number of containers. Scans may include unrelated neighbouring chests or repeated category labels; do not inspect or collect all candidates automatically. If multiple groups fit and the requested sources cannot be distinguished, ask the owner and pause rather than broadening the goal." + "\n"
            + "Observe the current signs/containers and inventory, then call update_task_plan with completion covering EVERY requested item, quantity and source/destination. For 'take everything' with unknown amounts, load group:gui then use ONE inspect_containers(targets) call for all observed container positions; use its counts to define the full contract and operate the still-open active_gui first. If the owner already specified exact quantities/containers, register them without a separate inspection tour. GUI inspection is allowed; gui_action/gui_batch/wait_gui item mutations or collection are blocked until this condition is defined. Do not invent dummy conditions or assume success from a sentence." + "\n"
            + "Use these current server facts to check all explicit user requirements. On the FINAL gui_action/gui_batch that will satisfy ALL owner requirements, set complete_task=true: the tool performs actual actions, closes/settles the menu and requests runtime verification in this same call, with no final model report round. For intermediate transfers set close_after=true when done with that menu, and optionally put the next open_gui in the SAME ordered tool batch. Do not close a menu in a separate model turn. When completion cannot be declared with the last GUI action (e.g. additional arrival), call update_task_plan with complete=true at the last step after satisfying it. Do not reopen containers solely to reconfirm quantities or emptiness already covered by complete live source_checks. Unknown/unloaded/double-container coverage still requires observation. Verified predicates do not replace additional user requirements." + "\n";
}
